# Generated by Django 4.0.1 on 2022-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_useranswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_full_name', models.CharField(max_length=70)),
                ('aa_username', models.CharField(max_length=30)),
                ('aa_email_id', models.EmailField(max_length=100)),
                ('aa_qn_cat', models.CharField(max_length=255)),
                ('aa_qn_name', models.CharField(max_length=255)),
                ('aa_qn_ans', models.CharField(max_length=255)),
                ('aa_crt_ans', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='quizquestion',
            fields=[
                ('qn_id', models.AutoField(primary_key=True, serialize=False)),
                ('qn_cat', models.CharField(max_length=255)),
                ('qn_title', models.CharField(max_length=255)),
                ('qn_name', models.CharField(max_length=255)),
                ('qn_opt1', models.CharField(max_length=255)),
                ('qn_opt2', models.CharField(max_length=255)),
                ('qn_opt3', models.CharField(max_length=255)),
                ('qn_opt4', models.CharField(max_length=255)),
                ('qn_ans', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='quiztopics',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_cat', models.CharField(max_length=255)),
                ('quiz_title', models.CharField(max_length=255)),
                ('quiz_desc', models.CharField(max_length=255)),
                ('quiz_url', models.CharField(default='', max_length=100)),
                ('quiz_thumb', models.ImageField(upload_to='MyQuiz/images')),
            ],
        ),
        migrations.CreateModel(
            name='useranswers',
            fields=[
                ('qn_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('qn_cat', models.CharField(max_length=255)),
                ('qn_name', models.CharField(max_length=255)),
                ('qn_ans', models.CharField(max_length=255)),
                ('crt_ans', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('mobie_number', models.CharField(max_length=70)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
