# Generated by Django 4.0.1 on 2022-01-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyQuizApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_useranswers',
        ),
    ]
