# Generated by Django 4.0.1 on 2022-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyQuizApp', '0004_rename_birth_date_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
