# Generated by Django 4.0.1 on 2022-01-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyQuizApp', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
