# Generated by Django 4.0.1 on 2022-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyQuizApp', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='quiz_id',
            field=models.IntegerField(default=1),
        ),
    ]
