# Generated by Django 4.0.1 on 2022-01-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyQuizApp', '0008_useranswers_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='quiz_id',
        ),
    ]
